# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/

image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.

variables:

  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:

  paths:

    - .cache/pip

    - venv/

before_script:
  - python --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install numpy
  - pip install matplotlib
  - pip install scipy

test-freefall:
  stage: test
  script:
    - python vsed.py > artifacts/vsed.log
    - python stokes.py > artifacts/stokes.log
  artifacts:
    paths:
      - artifacts/vsed.log
      - artifacts/stokes.log
      - artifacts/*.png

